title: Harini Suresh
url: "https://harinisuresh.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/"
 - name: "publications"
   link: "research"
 - name: "teaching etc."
   link: "projects"
 - name: "cv"
   link: "FINAL CV.pdf"
 - name: "contact"
   link: "contact"
